### ISSUE TITLE
Voronoi 3D error

### ISSUE THREAD

**Issue by nortikin** [portnov/sverchok-extra#12]
![Снимок экрана от 2020-04-21 16-42-09](https://user-images.githubusercontent.com/5783432/79873105-52ee6900-83ef-11ea-8464-d82b9241791b.png)
scale issue
![Снимок экрана от 2020-04-21 16-44-50](https://user-images.githubusercontent.com/5783432/79873193-71ecfb00-83ef-11ea-9bf3-8edafeaf1caf.png)

**Comment by portnov** [comment]
I don't think this is a "scale" issue.
The correct Voronoi diagram for this point is one point in (0,0,0) and several endless segments of plane. It should be something like
![Screenshot_20200421_191635](https://user-images.githubusercontent.com/284644/79876635-bdf66a80-8404-11ea-96e8-036e7d8c84a4.png)
but in 3D. Note that the triangles at the illustrations above are triangles only because we cut these areas with a circle; otherwise, there should be just endless rays. Similar picture we would have in 3D.
The problem is, there is currently no way to deal with such infinite segments of planes in Blender (you can't apply bisect modifier to infinite mesh, for example). For Voronoi 2D node, I implemented some algorithm of cutting such infinite areas manually. But for 3D such algorithm would be much more complex, so I've not implemented it yet. So such infinite segments / rays are just skipped instead.

**Comment by portnov** [comment]
This probably will have more sense if you change size of random vectors from all 1 to some random values:
![Screenshot_20200421_192603](https://user-images.githubusercontent.com/284644/79877740-0e21fc80-8406-11ea-8e9d-33ba8ca87398.png)
Play around with this setup. You'll see what happens when you set Float High too close to Float Low.

**Comment by portnov** [comment]
Compare also to 
![Screenshot_20200421_193445](https://user-images.githubusercontent.com/284644/79878740-36f6c180-8407-11ea-8fa6-3587d15ea84b.png)
(play around with Randomize value)...

**Comment by nortikin** [comment]
much a lot of thanks
